image: docker:latest

# stages:
#   - test

# lint:
#   stage: test
#   image: node:18.16.0
#   tags:
#     - docker
#   before_script:
#     - npm i -g pnpm@8.6.2
#     - pnpm -v
#   script:
#     - pnpm install
#     - pnpm lint
# # image: docker:20.10.16

# # # services:
# # #   - docker:20.10.16-dind

stages:
  - test
  - build

lint:
  stage: test
  image: node:18.16.0
  tags:
    - docker
  before_script:
    - echo "*** $CI_DEFAULT_BRANCH ***"
    - echo "*** $CI_COMMIT_BRANCH ***"
    - echo "*** $CI_BUILD_REF_NAME ***"
    - echo "*** $CI_COMMIT_REF_NAME ***"
    - echo "*** $CI_COMMIT_TAG ***"
    - npm i -g pnpm@8.6.2
    - pnpm -v
  script:
    - pnpm install
    - pnpm lint

build-images:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev-/ && $CI_DEFAULT_BRANCH == "master"' # This rule will be evaluated
      when: always
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: 'true'
  before_script:
    - docker login --username "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t registry.freewillgroup.com/sbabase/stock:dev-0.0.2 .
    # - docker push $CI_REGISTRY/$APP_NAME:${CI_COMMIT_TAG#*-}
    - docker push registry.freewillgroup.com/sbabase/stock:dev-0.0.2
  tags:
    - docker
